# name = input("Enter your name: ")
# sl = name[1:4]
# print("Substring from index 1 to 3 is:", sl)

# print("Length of your name is:", len(name))
# print("Your name in uppercase is:", name.upper())
# print("Your name in lowercase is:", name.lower())
# print("Is your name all uppercase?", name.isupper())
# print("Is your name all lowercase?", name.islower())
# print("Number of times 'a' appears in your name:", name.count('a'))
# print("Your name reversed is:", name[::-1])
# print("Your name with spaces removed:", name.replace(" ", ""))

# print("Your name split into words:", name.split())
# print("First character of your name is:", name[0])
# print("Last character of your name is:", name[-1])
# print("Does your name start with 'A'?", name.startswith('A'))
# print("Does your name end with 'n'?", name.endswith('n'))
# print("Index of first occurrence of 'e' in your name:", name.find('e'))
# print("Index of last occurrence of 'e' in your name:", name.rfind('e'))
# print("Your name centered with '*' padding:", name.center(20, '*'))
# print("Your name left-justified with '-' padding:", name.ljust(20, '-'))
# print("Your name right-justified with '-' padding:", name.rjust(20, '-'))
# print("Your name with leading and trailing spaces removed:", name.strip())

# print("Your name with leading spaces removed:", name.lstrip())
# print("Your name with trailing spaces removed:", name.rstrip())
# print("Your name with spaces replaced by '_':", name.replace(" ", "_"))
# print("Your name capitalized:", name.capitalize())
# print("Your name in title case:", name.title())
# print("Your name encoded in UTF-8:", name.encode('utf-8'))
# print("Your name in ASCII:", name.encode('ascii', 'ignore').decode('ascii'))
# print("Your name with tabs replaced by spaces:", name.replace("\t", " "))
# print("Your name with newlines replaced by spaces:", name.replace("\n", " "))
# print("Your name with double spaces replaced by single space:", name.replace("  ", " "))
# print("Your name with vowels removed:", ''.join([c for c in name if c.lower() not in 'aeiou']))
# print("Your name reversed word by word:", ' '.join(name.split()[::-1]))
# print("Your name with every second character:", name[::2])
# print("Your name with every third character:", name[::3])
# print("Your name repeated twice:", name * 2)

# print("Your name with hyphens between characters:", '-'.join(name))
# print("Your name with underscores between characters:", '_'.join(name))
# print("Your name with spaces between characters:", ' '.join(name))
# print("Your name with commas between characters:", ','.join(name))
# print("Your name with periods between characters:", '.'.join(name))
# print("Your name with semicolons between characters:", ';'.join(name))
# print("Your name with colons between characters:", ':'.join(name))
# print("Your name with slashes between characters:", '/'.join(name))
# print("Your name with backslashes between characters:", '\\'.join(name))
# print("Your name with pipes between characters:", '|'.join(name))
# print("Your name with asterisks between characters:", '*'.join(name))
# print("Your name with plus signs between characters:", '+'.join(name))
# print("Your name with equal signs between characters:", '='.join(name))
# print("Your name with tildes between characters:", '~'.join(name))
# print("Your name with carets between characters:", '^'.join(name))
# print("Your name with dollar signs between characters:", '$'.join(name))
# print("Your name with percent signs between characters:", '%'.join(name))

# print("My original name is:", name[0:]) 
# print(name[-4 : -1])
# print(name[1:4]) 


sentence = input("Enter a sentence: ")
words = sentence.split()
print("The words in the sentence are:", words)
sen2 = "He is studying in the \"University of California.\" . and lives in the city of Los Angeles."
print(sen2) 
for word in words:
     word.capitalize()
     print(word)

name = input("Enter your name: ")
print(f"Your name is: {name}")