# print("Your name split into words:", name.split())
# print("First character of your name is:", name[0])
# print("Last character of your name is:", name[-1])
# print("Does your name start with 'A'?", name.startswith('A'))
# print("Does your name end with 'n'?", name.endswith('n'))
# print("Index of first occurrence of 'e' in your name:", name.find('e'))
# print("Index of last occurrence of 'e' in your name:", name.rfind('e'))
# print("Your name centered with '*' padding:", name.center(20, '*'))
# print("Your name left-justified with '-' padding:", name.ljust(20, '-'))
# print("Your name right-justified with '-' padding:", name.rjust(20, '-'))
# print("Your name with leading and trailing spaces removed:", name.strip())
